#!/bin/bash


set -x

# udevadm info -a -p $(udevadm info -q path -n /dev/video0)

board="$1"
port="$2"

# https://gist.github.com/mdevaev/6eb65be689142e5ac16da7542f50830f
model="$(tr < /proc/device-tree/model -d '\000')"

case "$board" in
	"rpi2")
		case "$model" in
			"Raspberry Pi 2 Model B Rev 1.1")
				if [ "$port" == "1-1.5:1.0" ]; then exit 0; else exit 1; fi;;
			*) exit 0;;
		esac;;
	"rpi3")
		case "$model" in
			"Raspberry Pi 3 Model B Rev 1.2")
				if [ "$port" == "1-1.5:1.0" ]; then exit 0; else exit 1; fi;;
			"Raspberry Pi 3 Model B Plus Rev 1.3")
				if [ "$port" == "1-1.2:1.0" ]; then exit 0; else exit 1; fi;;
			*) exit 0;;
		esac;;
	"rpi4")
		case "$model" in
			"Raspberry Pi 4 Model B Rev 1.1" | "Raspberry Pi 4 Model B Rev 1.2" | "Raspberry Pi 4 Model B Rev 1.4" | "Raspberry Pi 4 Model B Rev 1.5")
				if [ "$port" == "1-1.4:1.0" ] || [ "$port" == "2-1:1.0" ]; then exit 0; else exit 1; fi;;
			*) exit 0;;
		esac;;
	*) exit 1;;
esac
